### ISSUE TITLE
ACRE Desyc error

### ISSUE THREAD

**Issue by freghar** [CntoDev/mods#4]
_From @chrisleaptrott on January 8, 2016 22:16_

Looking into a fix for this.

@BullHorn7 can you request to the devs that they give some way to disable that message or just have it pop up once. It is insane that it just sticks there and doesn't go away...and it keeps making the hint-click noise the whole time.

_Copied from original issue: CntoDev/cnto-mmt-repo#76_

**Comment by freghar** [comment]
_From @BullHorn7 on January 8, 2016 22:27_

Nope. The message is indicating a problem with the mission but the actual effect it may create might make it look like ACRE is bugged when in fact the bug has nothing to do with ACRE. To avoid false complaints, this message will not be removed until BI figure out how to fix the source of the inventory desync.

For the time being modifying the loadout script should solve this. I haven't seen the current loadout template so I can't help you there but the default F3 version I used last year didn't produce this error.

**Comment by freghar** [comment]
_From @chrisleaptrott on January 8, 2016 22:47_

They need to make it where it can be acknowledged and turned off. That's completely self-serving to want to avoid bug complaints by having something INCREDIBLY annoying just constantly up like that. I've got an idea for the fix according to some research, but that error....It needs to have some way to acknowledged it. Having it up for like 5 mins is more than enough. It doesn't need to persist.

Its a bad excuse.

**Comment by freghar** [comment]
_From @BullHorn7 on January 8, 2016 22:49_

I'll bug them about it but I won't be the first... Nou is very difficult to persuade.

**Comment by freghar** [comment]
_From @chrisleaptrott on January 8, 2016 22:50_

Yeah, I get you. It just ruined about 2 hours of footage we were hoping to use as promotional stuff.

**Comment by freghar** [comment]
_From @milivojm on January 12, 2016 10:22_

I've found the message and commented it out. It probably can't be tested as creating "desync" is not something we can do on purpose. But we might give it a try and see it doesn't break other things.

**Comment by freghar** [comment]
_From @chrisleaptrott on January 12, 2016 10:24_

Yeah, great job!

**Comment by freghar** [comment]
_From @milivojm on January 12, 2016 10:27_

I'll leave it here for future reference. The message was being called in fnc_monitorRadios.sqf in acre_sys_radio_2_1_0_811.pbo.

```
DFUNC(hasGearDesync) = {
	if(ACRE_SERVER_GEAR_DESYNCED) then {
		// Highway, 12.1.2016. - removed the annoying message
		// _message = "ACRE has determined that players in this mission have an inventory that has desynchronized from the server, this is due to a bug in the mission or a bug in Arma 3, NOT ACRE. This message will not dissappear and is a warning that ACRE may no longer be functioning correctly in this mission. The players experiencing the bug are listed below:\n\n";
		// {
		//	_message = _message + format["%1\n", name _x];
		// } forEach ACRE_SERVER_DESYNCED_PLAYERS;
		// hint _message;
		// diag_log text _message;
	};
};
```

I have just commented out the body of the if statement. We might need to do it on every ACRE update. :(

**Comment by freghar** [comment]
_From @BullHorn7 on January 12, 2016 15:48_

If you don't mind editing ACRE2 files (which we avoided for some reason in the past when I released the 5-volume slider change), I'd suggest you make the message show up but disappear after a while. It's still useful to know that there's a problem with inventories before thinking that something is just randomly wrong with the radios.

**Comment by milivojm** [comment]
Is this still actual? I see the fix is above. We didn't get this error for quite some time.

**Comment by freghar** [comment]
The "issue" is probably still there, but I don't think we have any means of fixing it other than modifying the mod and keeping the modifications local to us. :(

I guess we can close this, unless anyone has a good reason not to.
